;nombre: Jhosep Isaac Islam Chachagua
;25-0464-2017
TITLE EJERCICIO02
INCLUDE IRVINE32.INC
INCLUDE MACROS.INC
mCONSONANTES MACRO CA:REQ
	LOCAL VAR_CONS
	LOCAL CONT
	LOCAL CONT2
.DATA
	VAR_CONS BYTE  "BbCcDdFfGgHhJjKkLlMmNnPpQqRrSsTtVvWwXxYyZz",0
	CONT DWORD 0
	CONT2 DWORD 0	
.CODE
	MOV ESI, OFFSET CA
	MOV ECX, LENGTHOF CA
		
		; SE MANDAN A LA PILA LOS CARACTERES QUE SE VAN A PROCESAR
		L:MOV AL, [ESI]						
			PUSH EAX
			INC ESI
		LOOP L		
		
		
		MOV CONT2, 100		;CANTIDAD DE VECES QUE SE ITERARÁ
		L0: POP EAX ; 		SE EXTRAE UN ELEMENTO DE LA PILA
			MOV ESI, OFFSET VAR_CONS 
			MOV ECX, LENGTHOF VAR_CONS			
			L2:MOV BL, [ESI] ; SE EXTRAE UN ELEMENTO DE LA CADENA DE CONSONANTES
				.IF(AL == BL) ; COMPARANDO CARACTERES 
					INC CONT ; SI EL ELEMENTO QUE SE EXTRAJO DE LA PILA EXISTE EN LA CADENA DE CONSONANTES 
							;SE INCREMENTA EL CONTADO DE CONSONANTES
				.ENDIF
				ADD ESI, TYPE VAR_CONS
			LOOP L2			
			DEC CONT2
			CMP CONT2, 0 ; VALIDACION DE RECORRIDO DE L0
			JA  L0	
		CALL CRLF
		
		DEC CONT
		MOV EAX, CONT
		
		
ENDM
.DATA	
	VAR_CADENA BYTE  100 DUP(" ")
.CODE
	JI PROC		
		MWRITE "Ingrese una cadena: "
		MOV EDX, OFFSET VAR_CADENA ; ASIGNACION DEL BUFFER
		MOV ECX, LENGTHOF VAR_CADENA		
		CALL READSTRING	 ; LECTURA DE CADENA
		mCONSONANTES VAR_CADENA	 ;LLAMADA A LA MACROS
		
		MWRITE "Cantidad de Consonantes en la cadena: "
		CALL  WRITEDEC ; IMPRIMIR RESULTADOS
	EXIT
	JI ENDP 	
END JI